### Get Request
GET http://localhost:8000/api/v1/users


### Post Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json


### Put Method
PUT http://localhost:8000/api/v1/users
Content-Type: application/json
Authorization: special

{
    "id":2,
    "fName":"Ball",
    "lName":"Bhnadari"
}

### Delete Method
DELETE http://localhost:8000/api/v1/users/7
Content-Type: application/json
