### Get Request
GET http://localhost:8000?id=1&fName=Umesh&lName=Dhakal


### Post Method
POST http://localhost:8000
Content-Type: application/json

{
    "id":"3",
    "fName":"Sanjay", 
    "lName":"Karki"
}

### Put Method
PUT http://localhost:8000
Content-Type: application/json
Authorization: special

{
    "id":"2",
    "fName":"Ball",
    "lName":"Bhnadari"
}

### Delete Method
DELETE http://localhost:8000/4
Content-Type: application/json
